# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id_berita', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=255)),
                ('isi', models.TextField()),
                ('gambar_utama', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[(b'BU', b'Berita Utama/ Standard'), (b'SN', b'Slide News'), (b'CL', b'Karir/ Lowongan Kerja')], default=b'BU', max_length=100, null=True)),
                ('url', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('tanggal_post', models.DateTimeField(auto_now_add=True)),
                ('tangal_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-tangal_update', 'judul'),
                'db_table': 'Berita',
            },
        ),
    ]
