# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agenda', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('tempat', models.CharField(max_length=100)),
                ('tanggal', models.DateTimeField()),
                ('mulai', models.TimeField()),
                ('selesai', models.TimeField()),
                ('tanggal_post', models.DateTimeField(auto_now_add=True)),
                ('tangal_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-tangal_update', 'judul'),
                'db_table': 'Agenda',
            },
        ),
        migrations.RemoveField(
            model_name='berita',
            name='slug',
        ),
        migrations.AlterField(
            model_name='berita',
            name='gambar_utama',
            field=models.FileField(blank=True, upload_to=b'static/images/news/'),
        ),
        migrations.AlterField(
            model_name='berita',
            name='status',
            field=models.CharField(choices=[(b'P', b'Publish'), (b'U', b'Unpublish')], default=b'P', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='berita',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
