# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_delete_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agenda', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('tempat', models.CharField(max_length=100)),
                ('mulai', models.TimeField()),
                ('selesai', models.TimeField()),
                ('tanggal_post', models.DateTimeField(auto_now_add=True)),
                ('tangal_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-tangal_update', 'judul'),
                'db_table': 'Agenda',
            },
        ),
    ]
