# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='tanggal',
            field=models.DateTimeField(null=True),
        ),
    ]
