# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20160103_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='kategori',
            field=models.CharField(choices=[(b'Berita Utama/ Standard', b'Berita Utama/ Standard'), (b'Slide News', b'Slide News'), (b'Karir/ Lowongan Kerja', b'Karir/ Lowongan Kerja')], default=b'Berita Utama/ Standard', max_length=100, null=True),
        ),
    ]
